# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "trix"
pin "@rails/actiontext", to: "actiontext.esm.js"
pin "jquery"
pin "axios", to: "https://cdn.jsdelivr.net/npm/axios@1.7.9/dist/axios.min.js"
pin "components/like", to: "components/like.js"
pin "components/comment", to: "components/comment.js"
pin "modules/ajax", to: "modules/ajax.js"
pin "modules/axios", to: "modules/axios.js"
pin "modules/jquery", to: "modules/jquery.js"